# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mpdr/WHAREHOUSE/Programacao/CAL_NotPlanes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mpdr/WHAREHOUSE/Programacao/CAL_NotPlanes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mpdr/WHAREHOUSE/Programacao/CAL_NotPlanes/CMakeFiles /home/mpdr/WHAREHOUSE/Programacao/CAL_NotPlanes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mpdr/WHAREHOUSE/Programacao/CAL_NotPlanes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named airshuttle

# Build rule for target.
airshuttle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 airshuttle
.PHONY : airshuttle

# fast build rule for target.
airshuttle/fast:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/build
.PHONY : airshuttle/fast

src/AirShuttle/Reservation.o: src/AirShuttle/Reservation.cpp.o

.PHONY : src/AirShuttle/Reservation.o

# target to build an object file
src/AirShuttle/Reservation.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Reservation.cpp.o
.PHONY : src/AirShuttle/Reservation.cpp.o

src/AirShuttle/Reservation.i: src/AirShuttle/Reservation.cpp.i

.PHONY : src/AirShuttle/Reservation.i

# target to preprocess a source file
src/AirShuttle/Reservation.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Reservation.cpp.i
.PHONY : src/AirShuttle/Reservation.cpp.i

src/AirShuttle/Reservation.s: src/AirShuttle/Reservation.cpp.s

.PHONY : src/AirShuttle/Reservation.s

# target to generate assembly for a file
src/AirShuttle/Reservation.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Reservation.cpp.s
.PHONY : src/AirShuttle/Reservation.cpp.s

src/AirShuttle/Service.o: src/AirShuttle/Service.cpp.o

.PHONY : src/AirShuttle/Service.o

# target to build an object file
src/AirShuttle/Service.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Service.cpp.o
.PHONY : src/AirShuttle/Service.cpp.o

src/AirShuttle/Service.i: src/AirShuttle/Service.cpp.i

.PHONY : src/AirShuttle/Service.i

# target to preprocess a source file
src/AirShuttle/Service.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Service.cpp.i
.PHONY : src/AirShuttle/Service.cpp.i

src/AirShuttle/Service.s: src/AirShuttle/Service.cpp.s

.PHONY : src/AirShuttle/Service.s

# target to generate assembly for a file
src/AirShuttle/Service.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Service.cpp.s
.PHONY : src/AirShuttle/Service.cpp.s

src/AirShuttle/ServicesPlanner.o: src/AirShuttle/ServicesPlanner.cpp.o

.PHONY : src/AirShuttle/ServicesPlanner.o

# target to build an object file
src/AirShuttle/ServicesPlanner.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/ServicesPlanner.cpp.o
.PHONY : src/AirShuttle/ServicesPlanner.cpp.o

src/AirShuttle/ServicesPlanner.i: src/AirShuttle/ServicesPlanner.cpp.i

.PHONY : src/AirShuttle/ServicesPlanner.i

# target to preprocess a source file
src/AirShuttle/ServicesPlanner.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/ServicesPlanner.cpp.i
.PHONY : src/AirShuttle/ServicesPlanner.cpp.i

src/AirShuttle/ServicesPlanner.s: src/AirShuttle/ServicesPlanner.cpp.s

.PHONY : src/AirShuttle/ServicesPlanner.s

# target to generate assembly for a file
src/AirShuttle/ServicesPlanner.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/ServicesPlanner.cpp.s
.PHONY : src/AirShuttle/ServicesPlanner.cpp.s

src/AirShuttle/Van.o: src/AirShuttle/Van.cpp.o

.PHONY : src/AirShuttle/Van.o

# target to build an object file
src/AirShuttle/Van.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Van.cpp.o
.PHONY : src/AirShuttle/Van.cpp.o

src/AirShuttle/Van.i: src/AirShuttle/Van.cpp.i

.PHONY : src/AirShuttle/Van.i

# target to preprocess a source file
src/AirShuttle/Van.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Van.cpp.i
.PHONY : src/AirShuttle/Van.cpp.i

src/AirShuttle/Van.s: src/AirShuttle/Van.cpp.s

.PHONY : src/AirShuttle/Van.s

# target to generate assembly for a file
src/AirShuttle/Van.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/AirShuttle/Van.cpp.s
.PHONY : src/AirShuttle/Van.cpp.s

src/Algorithms/DFS.o: src/Algorithms/DFS.cpp.o

.PHONY : src/Algorithms/DFS.o

# target to build an object file
src/Algorithms/DFS.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/DFS.cpp.o
.PHONY : src/Algorithms/DFS.cpp.o

src/Algorithms/DFS.i: src/Algorithms/DFS.cpp.i

.PHONY : src/Algorithms/DFS.i

# target to preprocess a source file
src/Algorithms/DFS.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/DFS.cpp.i
.PHONY : src/Algorithms/DFS.cpp.i

src/Algorithms/DFS.s: src/Algorithms/DFS.cpp.s

.PHONY : src/Algorithms/DFS.s

# target to generate assembly for a file
src/Algorithms/DFS.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/DFS.cpp.s
.PHONY : src/Algorithms/DFS.cpp.s

src/Algorithms/GraphAlgorithm.o: src/Algorithms/GraphAlgorithm.cpp.o

.PHONY : src/Algorithms/GraphAlgorithm.o

# target to build an object file
src/Algorithms/GraphAlgorithm.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/GraphAlgorithm.cpp.o
.PHONY : src/Algorithms/GraphAlgorithm.cpp.o

src/Algorithms/GraphAlgorithm.i: src/Algorithms/GraphAlgorithm.cpp.i

.PHONY : src/Algorithms/GraphAlgorithm.i

# target to preprocess a source file
src/Algorithms/GraphAlgorithm.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/GraphAlgorithm.cpp.i
.PHONY : src/Algorithms/GraphAlgorithm.cpp.i

src/Algorithms/GraphAlgorithm.s: src/Algorithms/GraphAlgorithm.cpp.s

.PHONY : src/Algorithms/GraphAlgorithm.s

# target to generate assembly for a file
src/Algorithms/GraphAlgorithm.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Algorithms/GraphAlgorithm.cpp.s
.PHONY : src/Algorithms/GraphAlgorithm.cpp.s

src/Graph/Edge.o: src/Graph/Edge.cpp.o

.PHONY : src/Graph/Edge.o

# target to build an object file
src/Graph/Edge.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Edge.cpp.o
.PHONY : src/Graph/Edge.cpp.o

src/Graph/Edge.i: src/Graph/Edge.cpp.i

.PHONY : src/Graph/Edge.i

# target to preprocess a source file
src/Graph/Edge.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Edge.cpp.i
.PHONY : src/Graph/Edge.cpp.i

src/Graph/Edge.s: src/Graph/Edge.cpp.s

.PHONY : src/Graph/Edge.s

# target to generate assembly for a file
src/Graph/Edge.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Edge.cpp.s
.PHONY : src/Graph/Edge.cpp.s

src/Graph/Graph.o: src/Graph/Graph.cpp.o

.PHONY : src/Graph/Graph.o

# target to build an object file
src/Graph/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Graph.cpp.o
.PHONY : src/Graph/Graph.cpp.o

src/Graph/Graph.i: src/Graph/Graph.cpp.i

.PHONY : src/Graph/Graph.i

# target to preprocess a source file
src/Graph/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Graph.cpp.i
.PHONY : src/Graph/Graph.cpp.i

src/Graph/Graph.s: src/Graph/Graph.cpp.s

.PHONY : src/Graph/Graph.s

# target to generate assembly for a file
src/Graph/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Graph.cpp.s
.PHONY : src/Graph/Graph.cpp.s

src/Graph/Vertex.o: src/Graph/Vertex.cpp.o

.PHONY : src/Graph/Vertex.o

# target to build an object file
src/Graph/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Vertex.cpp.o
.PHONY : src/Graph/Vertex.cpp.o

src/Graph/Vertex.i: src/Graph/Vertex.cpp.i

.PHONY : src/Graph/Vertex.i

# target to preprocess a source file
src/Graph/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Vertex.cpp.i
.PHONY : src/Graph/Vertex.cpp.i

src/Graph/Vertex.s: src/Graph/Vertex.cpp.s

.PHONY : src/Graph/Vertex.s

# target to generate assembly for a file
src/Graph/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Graph/Vertex.cpp.s
.PHONY : src/Graph/Vertex.cpp.s

src/GraphViewer/cpp/connection.o: src/GraphViewer/cpp/connection.cpp.o

.PHONY : src/GraphViewer/cpp/connection.o

# target to build an object file
src/GraphViewer/cpp/connection.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/connection.cpp.o
.PHONY : src/GraphViewer/cpp/connection.cpp.o

src/GraphViewer/cpp/connection.i: src/GraphViewer/cpp/connection.cpp.i

.PHONY : src/GraphViewer/cpp/connection.i

# target to preprocess a source file
src/GraphViewer/cpp/connection.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/connection.cpp.i
.PHONY : src/GraphViewer/cpp/connection.cpp.i

src/GraphViewer/cpp/connection.s: src/GraphViewer/cpp/connection.cpp.s

.PHONY : src/GraphViewer/cpp/connection.s

# target to generate assembly for a file
src/GraphViewer/cpp/connection.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/connection.cpp.s
.PHONY : src/GraphViewer/cpp/connection.cpp.s

src/GraphViewer/cpp/graphviewer.o: src/GraphViewer/cpp/graphviewer.cpp.o

.PHONY : src/GraphViewer/cpp/graphviewer.o

# target to build an object file
src/GraphViewer/cpp/graphviewer.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/graphviewer.cpp.o
.PHONY : src/GraphViewer/cpp/graphviewer.cpp.o

src/GraphViewer/cpp/graphviewer.i: src/GraphViewer/cpp/graphviewer.cpp.i

.PHONY : src/GraphViewer/cpp/graphviewer.i

# target to preprocess a source file
src/GraphViewer/cpp/graphviewer.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/graphviewer.cpp.i
.PHONY : src/GraphViewer/cpp/graphviewer.cpp.i

src/GraphViewer/cpp/graphviewer.s: src/GraphViewer/cpp/graphviewer.cpp.s

.PHONY : src/GraphViewer/cpp/graphviewer.s

# target to generate assembly for a file
src/GraphViewer/cpp/graphviewer.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/GraphViewer/cpp/graphviewer.cpp.s
.PHONY : src/GraphViewer/cpp/graphviewer.cpp.s

src/Utils/GraphLoader.o: src/Utils/GraphLoader.cpp.o

.PHONY : src/Utils/GraphLoader.o

# target to build an object file
src/Utils/GraphLoader.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/GraphLoader.cpp.o
.PHONY : src/Utils/GraphLoader.cpp.o

src/Utils/GraphLoader.i: src/Utils/GraphLoader.cpp.i

.PHONY : src/Utils/GraphLoader.i

# target to preprocess a source file
src/Utils/GraphLoader.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/GraphLoader.cpp.i
.PHONY : src/Utils/GraphLoader.cpp.i

src/Utils/GraphLoader.s: src/Utils/GraphLoader.cpp.s

.PHONY : src/Utils/GraphLoader.s

# target to generate assembly for a file
src/Utils/GraphLoader.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/GraphLoader.cpp.s
.PHONY : src/Utils/GraphLoader.cpp.s

src/Utils/MapDrawer.o: src/Utils/MapDrawer.cpp.o

.PHONY : src/Utils/MapDrawer.o

# target to build an object file
src/Utils/MapDrawer.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/MapDrawer.cpp.o
.PHONY : src/Utils/MapDrawer.cpp.o

src/Utils/MapDrawer.i: src/Utils/MapDrawer.cpp.i

.PHONY : src/Utils/MapDrawer.i

# target to preprocess a source file
src/Utils/MapDrawer.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/MapDrawer.cpp.i
.PHONY : src/Utils/MapDrawer.cpp.i

src/Utils/MapDrawer.s: src/Utils/MapDrawer.cpp.s

.PHONY : src/Utils/MapDrawer.s

# target to generate assembly for a file
src/Utils/MapDrawer.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/MapDrawer.cpp.s
.PHONY : src/Utils/MapDrawer.cpp.s

src/Utils/Position.o: src/Utils/Position.cpp.o

.PHONY : src/Utils/Position.o

# target to build an object file
src/Utils/Position.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Position.cpp.o
.PHONY : src/Utils/Position.cpp.o

src/Utils/Position.i: src/Utils/Position.cpp.i

.PHONY : src/Utils/Position.i

# target to preprocess a source file
src/Utils/Position.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Position.cpp.i
.PHONY : src/Utils/Position.cpp.i

src/Utils/Position.s: src/Utils/Position.cpp.s

.PHONY : src/Utils/Position.s

# target to generate assembly for a file
src/Utils/Position.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Position.cpp.s
.PHONY : src/Utils/Position.cpp.s

src/Utils/Time.o: src/Utils/Time.cpp.o

.PHONY : src/Utils/Time.o

# target to build an object file
src/Utils/Time.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Time.cpp.o
.PHONY : src/Utils/Time.cpp.o

src/Utils/Time.i: src/Utils/Time.cpp.i

.PHONY : src/Utils/Time.i

# target to preprocess a source file
src/Utils/Time.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Time.cpp.i
.PHONY : src/Utils/Time.cpp.i

src/Utils/Time.s: src/Utils/Time.cpp.s

.PHONY : src/Utils/Time.s

# target to generate assembly for a file
src/Utils/Time.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/Utils/Time.cpp.s
.PHONY : src/Utils/Time.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/airshuttle.dir/build.make CMakeFiles/airshuttle.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... airshuttle"
	@echo "... edit_cache"
	@echo "... src/AirShuttle/Reservation.o"
	@echo "... src/AirShuttle/Reservation.i"
	@echo "... src/AirShuttle/Reservation.s"
	@echo "... src/AirShuttle/Service.o"
	@echo "... src/AirShuttle/Service.i"
	@echo "... src/AirShuttle/Service.s"
	@echo "... src/AirShuttle/ServicesPlanner.o"
	@echo "... src/AirShuttle/ServicesPlanner.i"
	@echo "... src/AirShuttle/ServicesPlanner.s"
	@echo "... src/AirShuttle/Van.o"
	@echo "... src/AirShuttle/Van.i"
	@echo "... src/AirShuttle/Van.s"
	@echo "... src/Algorithms/DFS.o"
	@echo "... src/Algorithms/DFS.i"
	@echo "... src/Algorithms/DFS.s"
	@echo "... src/Algorithms/GraphAlgorithm.o"
	@echo "... src/Algorithms/GraphAlgorithm.i"
	@echo "... src/Algorithms/GraphAlgorithm.s"
	@echo "... src/Graph/Edge.o"
	@echo "... src/Graph/Edge.i"
	@echo "... src/Graph/Edge.s"
	@echo "... src/Graph/Graph.o"
	@echo "... src/Graph/Graph.i"
	@echo "... src/Graph/Graph.s"
	@echo "... src/Graph/Vertex.o"
	@echo "... src/Graph/Vertex.i"
	@echo "... src/Graph/Vertex.s"
	@echo "... src/GraphViewer/cpp/connection.o"
	@echo "... src/GraphViewer/cpp/connection.i"
	@echo "... src/GraphViewer/cpp/connection.s"
	@echo "... src/GraphViewer/cpp/graphviewer.o"
	@echo "... src/GraphViewer/cpp/graphviewer.i"
	@echo "... src/GraphViewer/cpp/graphviewer.s"
	@echo "... src/Utils/GraphLoader.o"
	@echo "... src/Utils/GraphLoader.i"
	@echo "... src/Utils/GraphLoader.s"
	@echo "... src/Utils/MapDrawer.o"
	@echo "... src/Utils/MapDrawer.i"
	@echo "... src/Utils/MapDrawer.s"
	@echo "... src/Utils/Position.o"
	@echo "... src/Utils/Position.i"
	@echo "... src/Utils/Position.s"
	@echo "... src/Utils/Time.o"
	@echo "... src/Utils/Time.i"
	@echo "... src/Utils/Time.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

